### ISSUE TITLE
File upload looks successful but no file uploaded

### ISSUE THREAD

**Issue by joja19** [jogetworkflow/jw-community#10]
Hi ! 

I am using Joget 6 BETA on Redhat Linux 5.11 and imported the example CRM app from Joget 5 running on Windows 8. 

The CRM app on Joget 5 successfully creates the folder "wflow/app_formuploads" and I can browse to the files I have uploaded. 

The same CRM app on Joget 6 accepts the file upload but the directory "app_formuploads" is never created and I can never find the file in the filesystem.

N.B. On Linux Joget 6, I have a modified version of the database setup script, as we had to run under MyISAM engine in MySQL instead of InnoDB. and the modifications are:

**1) Byte size of composite varchar key was 1020 (250+90  * 3) and MyISAM is limited to 1000 bytes only:** 

===  original  ===
`CREATE TABLE `SHKToolAgentApp` (  `TOOL_AGENT_NAME` varchar(250) NOT NULL,  `APP_NAME` varchar(90) NOT NULL,
`

===  modified  ===
`CREATE TABLE `SHKToolAgentApp` (`TOOL_AGENT_NAME` varchar(100) NOT NULL,  `APP_NAME` varchar(25) NOT NULL, `

**2) All engine and encoding records in the SQL script were modified to MyISAM and Latin1.** 

I am not sure if this change may have impacted the file upload, but I can see:

`select * from SHKToolAgentApp;
`
returning empty set, and I guess that's because we are not using any tool in our app yet,

**Comment by jogetworkflow** [comment]
Hi there,

It's quite unlikely that the db change would affect the file upload directories. It's more likely to be your directory file permissions. If you have questions or discussions like this it's better to post on the community Q&A at http://answers.joget.org, issues here on GitHub should be detailed bug reports.
