### ISSUE TITLE
mvn install failed

### ISSUE THREAD

**Issue by amalminion** [jogetworkflow/jw-community#11]
I was unable to build whole packages. Can you guys update all dependency in pom files. Because some of it missing in maven repository.
![build failure](https://user-images.githubusercontent.com/32085422/30575130-4bc1ccb4-9d31-11e7-8be4-a10da0b6ae55.JPG)

**Comment by Owenong** [comment]
Hi, do you refer to the building guide in https://dev.joget.org/community/display/KBv5/Joget+Workflow+Source+Code?

**Comment by amalminion** [comment]
Thanks Owen. I managed to resolve this issue. Just notice that I missed out step#2 install 3rd party libraries.
