### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by unbendingWind** [jogetworkflow/jw-community#12]
mac ,https://dev.joget.org/community/display/KBv5/Joget+Workflow+Source+Code

but
`[INFO] wflow-jdbc ......................................... SUCCESS [  1.063 s]
[INFO] wflow-commons ...................................... SUCCESS [  1.881 s]
[INFO] wflow-plugin-base .................................. SUCCESS [  3.089 s]
[INFO] wflow-plugin-archetype ............................. SUCCESS [  0.478 s]
[INFO] wflow-directory .................................... SUCCESS [  6.144 s]
[INFO] wflow-wfengine ..................................... SUCCESS [  8.081 s]
[INFO] wflow-core ......................................... SUCCESS [ 15.636 s]
[INFO] wflow-consoleweb ................................... SUCCESS [ 16.758 s]
[INFO] wflow-designer ..................................... SUCCESS [  5.621 s]
[INFO] wflow-designerweb .................................. FAILURE [  0.680 s]
[INFO] wflow-app .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.679 s
[INFO] Finished at: 2017-12-25T18:55:04-08:00
[INFO] Final Memory: 163M/885M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo.webstart:webstart-maven-plugin:1.0-alpha-2:jnlp-download-servlet (default) on project wflow-designerweb: Result of /bin/sh -c "cd /Users/xr/work/test/jw-community-5.0-SNAPSHOT/wflow-designerweb/target/jnlp && /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/jarsigner -keystore /Users/xr/work/test/jw-community-5.0-SNAPSHOT/wflow-designerweb/src/main/jnlp/keyStore -storepass ****** -keypass ****** -signedjar /Users/xr/work/test/jw-community-5.0-SNAPSHOT/wflow-designerweb/target/jnlp/commons-codec-1.2.jar /Users/xr/work/test/jw-community-5.0-SNAPSHOT/wflow-designerweb/target/jnlp/unprocessed_commons-codec-1.2.jar wflow" execution is: '127'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wflow-designerweb`

**Comment by unbendingWind** [comment]
![1514259076465](https://user-images.githubusercontent.com/15900140/34339112-91f8aa88-e924-11e7-9ebc-ceb0def12425.jpg)

**Comment by jogetworkflow** [comment]
The error says "execution is '127'" when invoking jarsigner, which indicates that you do not have the JDK jarsigner available.

For general help and Q&A you should use the community Q&A at https://answers.joget.org
