### ISSUE TITLE
Code for use validator

### ISSUE THREAD

**Issue by barrerafabian** [jogetworkflow/jw-community#16]
Hi team, i´m needing a help please,   

Currently i would like  use bean shell to validate that a calculation number don´t be minor than 1,  with this code I can not make it work:

import java.util.Arrays;
import org.joget.apps.app.service.AppUtil;
import org.joget.apps.form.model.Element;
import org.joget.apps.form.model.Form;
import org.joget.apps.form.model.FormData;
import org.joget.apps.form.service.FormUtil;
import org.joget.commons.util.LogUtil;
 
public boolean validate(Element element, FormData formData, String[] values) {
 boolean result = true ;
 
 try {
		if(Integer.parseInt(values[0]) == 0){
   		formData.addFormError(subtotal, "Must be more than 1."); //change field id to your calculation field
    return false;
}else{
    return true;
	formData.addFormError(subtotal, "Es mayor que 1."); //change field id to your calculation field
}

    //do something
} catch (Exception e) {
    LogUtil.error("CRM app - Backend userview", e, "Error retrieving user department in Report category permission");
}
return result;
}
//call validate method with injected variable
return validate(element, formData, values);

Attached is the  LOG message . 
[joget _12-02.log](https://github.com/jogetworkflow/jw-community/files/2855053/joget._12-02.log)

Someone can help with this?

thanks

**Comment by jogetworkflow** [comment]
Hi there,

If you have questions or discussions like this please post on the community Q&A at https://answers.joget.org, issues here on GitHub should be detailed bug reports.

Thanks.
