### ISSUE TITLE
URL decode

### ISSUE THREAD

**Issue by alupuleasa** [jogetworkflow/jw-community#17]
Hello,

I have a Joget (vers 6.0.11) REST API and on GET method it doesn't decode the parameters from URL.

On your documentation I only saw encodeUrlParam:
https://dev.joget.org/community/display/KBv6/StringUtil

Please advice

**Comment by jogetworkflow** [comment]
Hi,

If you have questions or discussions like this it's better to post on the community Q&A at http://answers.joget.org, issues here on GitHub should be detailed bug reports.

Thanks.
