### ISSUE TITLE
Wrong path to jarsigner

### ISSUE THREAD

**Issue by thehappycoder** [jogetworkflow/jw-community#18]
I have the same problem as here https://github.com/jogetworkflow/jw-community/issues/12 and I believe it's a bug.

On my mac, `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/jarsigner` doesn't exist.

The correct path is:
`/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/jarsigner`

Temporary workaround that helped me:
```
sudo ln -s /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/jarsigner /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/jarsigner
```

**Comment by jogetworkflow** [comment]
Hi, 

You could be using the Java JRE instead of JDK, as per https://stackoverflow.com/questions/34531675/jarsigner-error-for-maven-build-using-java-1-8

For follow-up and general Q&A please use the community Q&A at https://answers.joget.org, thanks.
