### ISSUE TITLE
Renderning JSON response in the UI

### ISSUE THREAD

**Issue by ajsatix** [jogetworkflow/jw-community#24]
I am trying to use Joget to build a small app where UI will be Joget and Backend will be Mongo. I am using restheart ( https://restheart.org/) as an wrpper to coneal Mongo for Joget.

Is it possible to redenr the JSON response which I get from restheart to Joget UI?

**Comment by inamkloudlearn** [comment]
I am also facing the similar issue. I want to fetch the data from the rest api and render it using joget

**Comment by jogetworkflow** [comment]
Hi there,

If you have questions or discussions like this it's better to post on the community Q&A at https://answers.joget.org, issues here on GitHub should be detailed bug reports.

Thanks!
