### ISSUE TITLE
wflow-install dependencies

### ISSUE THREAD

**Issue by prowave** [jogetworkflow/jw-community#3]
When building from wflow-install, some of the required artifacts are not available:

[ERROR] Failed to execute goal on project wflow-jdbc: Could not resolve dependencies for project org.joget:wflow-jdbc:jar:4.0-SNAPSHOT: The following artifacts could not be resolved: com.oracle:ojdbc6:jar:12.1.0.2, com.microsoft:sqljdbc:jar:4.0: Could not find artifact com.oracle:ojdbc6:jar:12.1.0.2 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

Perhaps you could add the repository definitions on the POM so that your project can more easily be built.

**Comment by jogetworkflow** [comment]
Hi, there are no public repository definitions at the moment, but here are the steps on building the project http://dev.joget.org/community/display/KBv5/Joget+Workflow+Source+Code

**Comment by jogetworkflow** [comment]
FYI there are now more detailed step-by-step guides at https://dev.joget.org/community/display/KBv5/Build+Source+Code+on+Linux and https://dev.joget.org/community/display/KBv5/Build+Source+Code+on+Windows
