### ISSUE TITLE
Cannot build wflow-app

### ISSUE THREAD

**Issue by kalwar** [jogetworkflow/jw-community#4]
[ERROR] Failed to execute goal on project wflow-jdbc: Could not resolve dependencies for project org.joget:wflow-jdbc:jar:5.0-RC9: The following artifacts could not be resolved: com.oracle:ojdbc6:jar:12.1.0.2, com.microsoft:sqljdbc:jar:4.0: Could not find artifact com.oracle:ojdbc6:jar:12.1.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by kalwar** [comment]
Must Download and install: "install-libraries.zip." from here:
http://dev.joget.org/community/display/KBv5/Joget+Workflow+Source+Code#JogetWorkflowSourceCode-1.InstallPrerequisites 

However, still getting this error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project wflow-core: There are test failures.

**Comment by jogetworkflow** [comment]
Hi, without more details on the error it's pretty hard to tell the cause of failure. You can post your question with more detailed information in the community site http://dev.joget.org/community/questions

**Comment by jogetworkflow** [comment]
FYI there are now more detailed step-by-step guides at https://dev.joget.org/community/display/KBv5/Build+Source+Code+on+Linux and https://dev.joget.org/community/display/KBv5/Build+Source+Code+on+Windows
