### ISSUE TITLE
checkout problem in eclipse?

### ISSUE THREAD

**Issue by Somshankar** [jogetworkflow/jw-community#5]
when a add new svn repositories add url at that clicking finish button  asking a user name and password , what is the user name and password.

**Comment by jogetworkflow** [comment]
Hi, not sure what you mean, but there are steps to build the project at http://dev.joget.org/community/display/KBv5/Joget+Workflow+Source+Code. You can post questions in the community site http://dev.joget.org/community/questions. Thanks.
