### ISSUE TITLE
Email Tool unable to attach multiple files upload per form field

### ISSUE THREAD

**Issue by gohkhoonhiang** [jogetworkflow/jw-community#6]
When the form File Upload field allows for multiple uploads, Email Tool is unable to read the multiple file names and attach each file.

![image](https://cloud.githubusercontent.com/assets/1378570/14414500/83030de6-ffc6-11e5-820b-58537d3f64c3.png)

![image](https://cloud.githubusercontent.com/assets/1378570/14414524/dbf5634a-ffc6-11e5-9255-c93fcb361003.png)

The following error occurs:

INFO  08 Apr 2016 15:17:07 org.joget.apps.app.lib.EmailTool  - Attached file fail from field "file1" in form "mpd_request_attach"

**Comment by jogetworkflow** [comment]
Thank for reporting this issue. We will check on it.

**Comment by jogetworkflow** [comment]
This has been fixed in 5.0.3, thanks!
