### ISSUE TITLE
DataListBinder plugin does not support property type 'grid'

### ISSUE THREAD

**Issue by gohkhoonhiang** [jogetworkflow/jw-community#7]
When developing a DataListBinder plugin, I used a 'grid' type property for the plugin.

![image](https://cloud.githubusercontent.com/assets/1378570/14488037/bd8ce8d2-0198-11e6-8eb7-2fc6b353847c.png)

However, the DataListBuilderWebController does not seem to parse 'grid' type property values. I get null everytime from the property.

**Comment by jogetworkflow** [comment]
Thank for reporting this issue. We will check on it.

**Comment by jogetworkflow** [comment]
This has been fixed in 5.0.3, thanks!
