### ISSUE TITLE
Suggestion: Resolve hash variable as default value for form field

### ISSUE THREAD

**Issue by gohkhoonhiang** [jogetworkflow/jw-community#8]
Hi,

I was creating a nested hash variable for my form.

```
#user.{form.tps_mpd_req_form.tps_mpd_pln_ack_user}.firstName#
```

The nested variable may contain a null value if the user has not processed the request. This caused the entire hash variable processing to fail and the literal string is displayed.

![image](https://cloud.githubusercontent.com/assets/1378570/16480188/4a151f1a-3ed7-11e6-80a5-dfa3367cca63.png)

This will become confusing to user.

Is it possible for you to enhance the hash variable logic to display an empty field when the nested variable is null?

Thank you!

**Comment by gohkhoonhiang** [comment]
Hi,

It seems to be a problem with me putting that hash variable in the 'value' field of the form field.

![image](https://cloud.githubusercontent.com/assets/1378570/16481974/7343e9b2-3ee0-11e6-905c-631b6dd8345d.png)

Even when I have a valid value for the field, the hash variable is not being resolved, and the literal value from the DB is displayed.

![image](https://cloud.githubusercontent.com/assets/1378570/16482046/c00ed554-3ee0-11e6-8ccf-92f37ba4105d.png)

Is it possible for the 'value' field to be some kind of 'default value' which can be resolved from a hash variable?

Your consideration of this feature is much appreciated.

Thanks!

**Comment by mattkjw** [comment]
Hi Ms Goh

The Joget Marketplace has a plugin call [Beanshell Hash Variable Plugin](https://marketplace.joget.org/jw/web/userview/mp/mpp/_/vad?id=beanshell_hash_variable-v1) that might interest you, it performs an if-else checking before populating the field in Joget v5.

Do take note that the #form.# hash variable tries to retrieves the value from the database before the form displays all the fields on screen (and not during data entry). A #form.# hash variable will not work to populate say, fieldB while fieldA is being data entry in the same form (for this you have to use java scripting).

Hope this helps.

**Comment by mattkjw** [comment]
Hi Ms Goh

Joget Workflow has an active community-wide [question and answer website] (https://dev.joget.org/community/questions?&filter=recent) which you might find helpful too.

**Comment by gohkhoonhiang** [comment]
Hi Matthew,

Thank you for sharing about the plugin. It seems like something I'm looking for.

I will remember to go to the Q&A website in the future for my questions.

Thanks!
