### ISSUE TITLE
About Distribution Transaction 

### ISSUE THREAD

**Issue by a78239636** [jogetworkflow/jw-community#82]
Hi, Thank you for your excellent work. I am using joget and learn the code. 
I found out that distributed transaction (bitronix)  is used in commonsApplication.xml, But I'm confused why distributed transactions are needed（seemed just one Datasource), and I haven't seen where this  are used,  just found transactionTemplate was used in publish App, like noraml transaction.
Can you help me with my doubts?

**Comment by owen-joget** [comment]
Hi,

Joget does not use distributed transactions. Among a few JTA-compliant transaction managers, e.g., Atomikos, Bitronix Transaction Manager (BTM), Java Open Transaction Manager (JOTM), we tested Bitronix which had better performance working with our platform. That is why it was chosen.
